// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/orders.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================================
// DRINK MESSAGE DEFINITION
// Represents a drink item that can be ordered
// ============================================================================
// Message to represent a single drink with its properties
type Drink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the drink
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the drink (e.g., "Spritzer", "Beer", "Coffee")
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Price of the drink in currency units
	Price int32 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// Description of the drink
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_pb_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Drink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drink) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Drink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ============================================================================
// DRINKS LIST MESSAGE
// Container for returning multiple drinks from GetDrinks RPC
// ============================================================================
// Message to hold a list of drinks returned by GetDrinks
type DrinkList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Array of Drink messages
	Drinks        []*Drink `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrinkList) Reset() {
	*x = DrinkList{}
	mi := &file_pb_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrinkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrinkList) ProtoMessage() {}

func (x *DrinkList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrinkList.ProtoReflect.Descriptor instead.
func (*DrinkList) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{1}
}

func (x *DrinkList) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

// ============================================================================
// ORDER REQUEST MESSAGE
// Request message for ordering drinks
// ============================================================================
// Message sent by client to order a specific drink
type OrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the drink to order
	DrinkId int32 `protobuf:"varint,1,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	// Quantity of drinks to order
	Quantity      int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_pb_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{2}
}

func (x *OrderRequest) GetDrinkId() int32 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

func (x *OrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ============================================================================
// ORDER ITEM MESSAGE
// Represents an individual order item with drink details and quantity
// ============================================================================
// Message representing a single order item in the order list
type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The drink that was ordered
	Drink *Drink `protobuf:"bytes,1,opt,name=drink,proto3" json:"drink,omitempty"`
	// Total quantity ordered of this drink
	Quantity      int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_pb_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItem) GetDrink() *Drink {
	if x != nil {
		return x.Drink
	}
	return nil
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ============================================================================
// ORDER LIST MESSAGE
// Container for returning all orders from GetOrders RPC
// ============================================================================
// Message to hold the complete list of orders
type OrderList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Array of OrderItem messages representing all orders
	Orders        []*OrderItem `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_pb_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{4}
}

func (x *OrderList) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_pb_orders_proto protoreflect.FileDescriptor

const file_pb_orders_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/orders.proto\x12\x06models\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"2\n" +
	"\tDrinkList\x12%\n" +
	"\x06drinks\x18\x01 \x03(\v2\r.models.DrinkR\x06drinks\"E\n" +
	"\fOrderRequest\x12\x19\n" +
	"\bdrink_id\x18\x01 \x01(\x05R\adrinkId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"L\n" +
	"\tOrderItem\x12#\n" +
	"\x05drink\x18\x01 \x01(\v2\r.models.DrinkR\x05drink\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"6\n" +
	"\tOrderList\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.models.OrderItemR\x06orders2\xbe\x01\n" +
	"\fOrderService\x126\n" +
	"\tGetDrinks\x12\x16.google.protobuf.Empty\x1a\x11.models.DrinkList\x12>\n" +
	"\n" +
	"OrderDrink\x12\x14.models.OrderRequest\x1a\x1a.google.protobuf.BoolValue\x126\n" +
	"\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x11.models.OrderListB\tZ\aexc8/pbb\x06proto3"

var (
	file_pb_orders_proto_rawDescOnce sync.Once
	file_pb_orders_proto_rawDescData []byte
)

func file_pb_orders_proto_rawDescGZIP() []byte {
	file_pb_orders_proto_rawDescOnce.Do(func() {
		file_pb_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)))
	})
	return file_pb_orders_proto_rawDescData
}

var file_pb_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_orders_proto_goTypes = []any{
	(*Drink)(nil),                // 0: models.Drink
	(*DrinkList)(nil),            // 1: models.DrinkList
	(*OrderRequest)(nil),         // 2: models.OrderRequest
	(*OrderItem)(nil),            // 3: models.OrderItem
	(*OrderList)(nil),            // 4: models.OrderList
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil), // 6: google.protobuf.BoolValue
}
var file_pb_orders_proto_depIdxs = []int32{
	0, // 0: models.DrinkList.drinks:type_name -> models.Drink
	0, // 1: models.OrderItem.drink:type_name -> models.Drink
	3, // 2: models.OrderList.orders:type_name -> models.OrderItem
	5, // 3: models.OrderService.GetDrinks:input_type -> google.protobuf.Empty
	2, // 4: models.OrderService.OrderDrink:input_type -> models.OrderRequest
	5, // 5: models.OrderService.GetOrders:input_type -> google.protobuf.Empty
	1, // 6: models.OrderService.GetDrinks:output_type -> models.DrinkList
	6, // 7: models.OrderService.OrderDrink:output_type -> google.protobuf.BoolValue
	4, // 8: models.OrderService.GetOrders:output_type -> models.OrderList
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_orders_proto_init() }
func file_pb_orders_proto_init() {
	if File_pb_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_orders_proto_goTypes,
		DependencyIndexes: file_pb_orders_proto_depIdxs,
		MessageInfos:      file_pb_orders_proto_msgTypes,
	}.Build()
	File_pb_orders_proto = out.File
	file_pb_orders_proto_goTypes = nil
	file_pb_orders_proto_depIdxs = nil
}
